language: objective-c
osx_image: xcode7

before_install:
- gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && xcodebuild -project SwiftParse.xcodeproj -scheme SwiftParse-OSX -sdk macosx ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c -f `xcpretty-travis-formatter`
- set -o pipefail && xcodebuild -project SwiftParse.xcodeproj -scheme SwiftCheck-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c -f `xcpretty-travis-formatter`